#pragma once

#ifndef SEED_DIAGNOSTICS_ENABLED
    #ifdef SEED_DEBUG
        #define SEED_DIAGNOSTICS_ENABLED 1
    #else
        #define SEED_DIAGNOSTICS_ENABLED 0
    #endif
#endif

#define SEED_DIAGNOSTICS_EVENT_TIMELINE     SEED_DIAGNOSTICS_ENABLED
#define SEED_DIAGNOSTICS_ECS_VALIDATION     SEED_DIAGNOSTICS_ENABLED
#define SEED_DIAGNOSTICS_MEMORY_VALIDATION  SEED_DIAGNOSTICS_ENABLED
#define SEED_DIAGNOSTICS_HEALTH_SCORE       SEED_DIAGNOSTICS_ENABLED
#define SEED_DIAGNOSTICS_SNAPSHOT_DUMP     SEED_DIAGNOSTICS_ENABLED
#define SEED_DIAGNOSTICS_ASSERT_LOG         SEED_DIAGNOSTICS_ENABLED

#ifndef SEED_DIAGNOSTICS_MAX_EVENTS
    #define SEED_DIAGNOSTICS_MAX_EVENTS 4096
#endif

#ifndef SEED_DIAGNOSTICS_MAX_SNAPSHOT_DEPTH
    #define SEED_DIAGNOSTICS_MAX_SNAPSHOT_DEPTH 8
#endif
